-- Primeiro, vamos verificar se o banco existe e conectar
CREATE DATABASE IF NOT EXISTS CRUD;
USE CRUD;

-- Remover tabelas existentes se necessário (cuidado com dados!)
-- DROP TABLE IF EXISTS produtos;
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS categorias;
-- DROP TABLE IF EXISTS capivara;

-- Ou alterar tabelas existentes para adicionar timestamps
-- Tabela users
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Tabela categorias  
ALTER TABLE categorias 
ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Tabela produtos
ALTER TABLE produtos 
ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Tabela capivara
ALTER TABLE capivara 
ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Verificar estrutura das tabelas
DESCRIBE users;
DESCRIBE categorias;  
DESCRIBE produtos;
DESCRIBE capivara;